### ISSUE TITLE
Missing files for Sart OpenCL tests when installed from wheel

### ISSUE THREAD

**Issue by jacklovell** [cherab/core#205]
Steps to reproduce:

1. Install raysect and cherab-core in a clean environment (where no installation in develop mode is present) from a wheel. I found this using a local wheel, but I suspect PyPI wheels will have the same issue.
1. Install `pyopencl` from PyPI to ensure the OpenCL tests will be run.
1. Run the unit tests for cherab: `python -m unittest discover cherab` from within the environment's site-packages directory.

First error:
```
(cherab-wheeltest) jlovell@jlovell-thinkpad:~/Software/anaconda3/envs/cherab-wheeltest/lib/python3.7/site-packages$ python -m unittest discover cherab
......................................................................................................................................................................................................................................................................................................................................................................................................................EEE................................
======================================================================
ERROR: test_inversion (tools.tests.test_sart_opencl.TestSartOpencl)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jlovell/Software/anaconda3/envs/cherab-wheeltest/lib/python3.7/site-packages/cherab/tools/tests/test_sart_opencl.py", line 42, in setUp
    gm = np.load(os.path.join(os.path.dirname(__file__), 'data/geometry_matrix.npy'))
  File "/home/jlovell/Software/anaconda3/envs/cherab-wheeltest/lib/python3.7/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/jlovell/Software/anaconda3/envs/cherab-wheeltest/lib/python3.7/site-packages/cherab/tools/tests/data/geometry_matrix.npy'

======================================================================
ERROR: test_inversion_atomic (tools.tests.test_sart_opencl.TestSartOpencl)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jlovell/Software/anaconda3/envs/cherab-wheeltest/lib/python3.7/site-packages/cherab/tools/tests/test_sart_opencl.py", line 42, in setUp
    gm = np.load(os.path.join(os.path.dirname(__file__), 'data/geometry_matrix.npy'))
  File "/home/jlovell/Software/anaconda3/envs/cherab-wheeltest/lib/python3.7/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/jlovell/Software/anaconda3/envs/cherab-wheeltest/lib/python3.7/site-packages/cherab/tools/tests/data/geometry_matrix.npy'

======================================================================
ERROR: test_inversion_constrained (tools.tests.test_sart_opencl.TestSartOpencl)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jlovell/Software/anaconda3/envs/cherab-wheeltest/lib/python3.7/site-packages/cherab/tools/tests/test_sart_opencl.py", line 42, in setUp
    gm = np.load(os.path.join(os.path.dirname(__file__), 'data/geometry_matrix.npy'))
  File "/home/jlovell/Software/anaconda3/envs/cherab-wheeltest/lib/python3.7/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/jlovell/Software/anaconda3/envs/cherab-wheeltest/lib/python3.7/site-packages/cherab/tools/tests/data/geometry_matrix.npy'

----------------------------------------------------------------------
Ran 441 tests in 41.107s

FAILED (errors=3)
```
There is missing test data here: the `.npy` files in the `data` directory should be copied into the wheel.

Second error (after copying the data directory):
```
(cherab-wheeltest) jlovell@jlovell-thinkpad:~/Software/anaconda3/envs/cherab-wheeltest/lib/python3.7/site-packages$ python -m unittest discover cherab
......................................................................................................................................................................................................................................................................................................................................................................................................................
Selected OpenCL device: Intel Intel(R) HD Graphics Kabylake ULT GT2

E
Selected OpenCL device: Intel Intel(R) HD Graphics Kabylake ULT GT2

E
Selected OpenCL device: Intel Intel(R) HD Graphics Kabylake ULT GT2

E................................
======================================================================
ERROR: test_inversion (tools.tests.test_sart_opencl.TestSartOpencl)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jlovell/Software/anaconda3/envs/cherab-wheeltest/lib/python3.7/site-packages/cherab/tools/tests/test_sart_opencl.py", line 53, in test_inversion
    steps_per_thread=64, block_size_row_maj=64) as inv_sart:
  File "/home/jlovell/Software/anaconda3/envs/cherab-wheeltest/lib/python3.7/site-packages/cherab/tools/inversions/opencl/sart_opencl.py", line 101, in __init__
    with open(kernel_source_file) as f_kernel:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jlovell/Software/anaconda3/envs/cherab-wheeltest/lib/python3.7/site-packages/cherab/tools/inversions/opencl/sart_kernels.cl'

======================================================================
ERROR: test_inversion_atomic (tools.tests.test_sart_opencl.TestSartOpencl)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jlovell/Software/anaconda3/envs/cherab-wheeltest/lib/python3.7/site-packages/cherab/tools/tests/test_sart_opencl.py", line 59, in test_inversion_atomic
    steps_per_thread=64, block_size_row_maj=64) as inv_sart:
  File "/home/jlovell/Software/anaconda3/envs/cherab-wheeltest/lib/python3.7/site-packages/cherab/tools/inversions/opencl/sart_opencl.py", line 101, in __init__
    with open(kernel_source_file) as f_kernel:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jlovell/Software/anaconda3/envs/cherab-wheeltest/lib/python3.7/site-packages/cherab/tools/inversions/opencl/sart_kernels_atomic.cl'

======================================================================
ERROR: test_inversion_constrained (tools.tests.test_sart_opencl.TestSartOpencl)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jlovell/Software/anaconda3/envs/cherab-wheeltest/lib/python3.7/site-packages/cherab/tools/tests/test_sart_opencl.py", line 68, in test_inversion_constrained
    steps_per_thread=64, block_size_row_maj=64) as inv_sart:
  File "/home/jlovell/Software/anaconda3/envs/cherab-wheeltest/lib/python3.7/site-packages/cherab/tools/inversions/opencl/sart_opencl.py", line 101, in __init__
    with open(kernel_source_file) as f_kernel:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jlovell/Software/anaconda3/envs/cherab-wheeltest/lib/python3.7/site-packages/cherab/tools/inversions/opencl/sart_kernels.cl'

----------------------------------------------------------------------
Ran 441 tests in 40.654s

FAILED (errors=3)
```
The OpenCL kernels are missing from the installation. This is a more serious issue than missing test data, as this will affect users who want to use this feature in their own codes.

After copying the `.cl` files into the installation directory the tests run successfully.

We should ensure that the `.npy` test data and certainly the `.cl` kernels are present in the distributed wheels.

**Comment by vsnever** [comment]
Sorry, never worked with setup scripts before. Should we add something like this?
```
setup(
...
    package_data={'': ['cherab/tools/inversions/opencl/*.cl', 'cherab/tools/tests/data/*.npy']},
...
) 
```
Do we need to modify MANIFEST.in as well?

**Comment by jacklovell** [comment]
I'm not sure: packaging isn't something I know much about. Could @CnlPepper or @mattngc offer some advice?

**Comment by CnlPepper** [comment]
You just need to add the relevant files/glob to the MAINIFEST.in file to ensure they are added to the package. See the raysect manifest file as an example: https://github.com/raysect/source/blob/master/MANIFEST.in

Adding *.npy and *.cl should resolve the issue. I assume these are the only file types involved? If there are any others, we'll need to add the too.

**Comment by CnlPepper** [comment]
I went ahead and made the change. If this resolves the issue then please close it.

**Comment by jacklovell** [comment]
Adding those globs to the manifest solves this issue.
