### ISSUE TITLE
"pip install cherab" fails with python 3.8.3

### ISSUE THREAD

**Issue by drsmith48** [cherab/core#223]
`pip install cherab` fails with python 3.8.3, but is successful for python 3.7.7.

On MacOS 10.13, I created a clean anaconda environment with cherab requirements:
`conda create -npy38 python=3.8 cython scipy matplotlib numpy`

I logged a verbose install:
`pip install -v cherab &> cherab_install.log`

Error in log:
```
Non-user install because site-packages writeable
Created temporary directory: /private/var/folders/d3/rrgnwv_j4xl19brwwb80g4qjmg31yq/T/pip-ephem-wheel-cache-vcrkgv13
Created temporary directory: /private/var/folders/d3/rrgnwv_j4xl19brwwb80g4qjmg31yq/T/pip-req-tracker-3kmeupa0
Initialized build tracking at /private/var/folders/d3/rrgnwv_j4xl19brwwb80g4qjmg31yq/T/pip-req-tracker-3kmeupa0
Created build tracker: /private/var/folders/d3/rrgnwv_j4xl19brwwb80g4qjmg31yq/T/pip-req-tracker-3kmeupa0
Entered build tracker: /private/var/folders/d3/rrgnwv_j4xl19brwwb80g4qjmg31yq/T/pip-req-tracker-3kmeupa0
Created temporary directory: /private/var/folders/d3/rrgnwv_j4xl19brwwb80g4qjmg31yq/T/pip-install-b8zmx0pe
1 location(s) to search for versions of cherab:
* https://pypi.org/simple/cherab/
Fetching project page and analyzing links: https://pypi.org/simple/cherab/
Getting page https://pypi.org/simple/cherab/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/cherab/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/cherab/ HTTP/1.1" 304 0
  Found link https://files.pythonhosted.org/packages/a8/1d/4925e33ff2cfe1a4a44f2d658d90d3484e4da39a47e8f93cf41f39ffec54/cherab-1.0.0.tar.gz#sha256=07304b11533d7281feb236be7c4aada2f632f7c9fb776a5015f1ae783d0d6f2d (from https://pypi.org/simple/cherab/), version: 1.0.0
  Found link https://files.pythonhosted.org/packages/6d/84/dd27a8cde24fe2a2157d52d6b1235c059b162cb6606ff618523df39ff53c/cherab-1.0.1.tar.gz#sha256=7545ec1325bd052704594a0169a0f9594523d56b08f0e4477d64df4a16a252f6 (from https://pypi.org/simple/cherab/), version: 1.0.1
  Found link https://files.pythonhosted.org/packages/3c/00/18769ea3a954b78b5e6cf9d5ab1772468b281ffcd4d9d07f2ff834d5b0be/cherab-1.1.0.tar.gz#sha256=bf218213a98aab61d25a26202f05a8aa776c5800a2ae5de44d38f21089e1f0d8 (from https://pypi.org/simple/cherab/), version: 1.1.0
  Skipping link: none of the wheel's tags match: cp36-cp36m-manylinux1_x86_64: https://files.pythonhosted.org/packages/06/c3/99d1b90e072505cb7b4e8c00426edd30d362a735358714d2375753f0ab37/cherab-1.2.0-cp36-cp36m-manylinux1_x86_64.whl#sha256=eea3424af9f5db0225a1e0797e153722bac19f72a87794d2c5310e595d1c6158 (from https://pypi.org/simple/cherab/)
  Skipping link: none of the wheel's tags match: cp37-cp37m-manylinux1_x86_64: https://files.pythonhosted.org/packages/32/a5/724b5ce02ff946cd913ee9c25e7f2453b30f18d9c0cc94ffcd44b76fb600/cherab-1.2.0-cp37-cp37m-manylinux1_x86_64.whl#sha256=1251d8733c9dd132307368169f68d3e2137f49f34927b82faa0928cc26713236 (from https://pypi.org/simple/cherab/)
  Found link https://files.pythonhosted.org/packages/01/1f/4756e757b740056a08b569acf01a09ce82b7094ccfb53e881ece08b4bdd8/cherab-1.2.0.tar.gz#sha256=92510a886dc68f9a13bc05dc46aa9881ff61fbd02ecbb40d3a2d6a9f2611358e (from https://pypi.org/simple/cherab/), version: 1.2.0
Given no hashes to check 4 links for project 'cherab': discarding no candidates
Using version 1.2.0 (newest of versions: 1.0.0, 1.0.1, 1.1.0, 1.2.0)
Collecting cherab
  Created temporary directory: /private/var/folders/d3/rrgnwv_j4xl19brwwb80g4qjmg31yq/T/pip-unpack-_2e15y99
  Looking up "https://files.pythonhosted.org/packages/01/1f/4756e757b740056a08b569acf01a09ce82b7094ccfb53e881ece08b4bdd8/cherab-1.2.0.tar.gz" in the cache
  Current age based on date: 10513966
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 10513966
  Using cached cherab-1.2.0.tar.gz (8.3 MB)
  Added cherab from https://files.pythonhosted.org/packages/01/1f/4756e757b740056a08b569acf01a09ce82b7094ccfb53e881ece08b4bdd8/cherab-1.2.0.tar.gz#sha256=92510a886dc68f9a13bc05dc46aa9881ff61fbd02ecbb40d3a2d6a9f2611358e to build tracker '/private/var/folders/d3/rrgnwv_j4xl19brwwb80g4qjmg31yq/T/pip-req-tracker-3kmeupa0'
    Running setup.py (path:/private/var/folders/d3/rrgnwv_j4xl19brwwb80g4qjmg31yq/T/pip-install-b8zmx0pe/cherab/setup.py) egg_info for package cherab
    Created temporary directory: /private/var/folders/d3/rrgnwv_j4xl19brwwb80g4qjmg31yq/T/pip-pip-egg-info-b5opcy6g
    Running command python setup.py egg_info
    Compiling cherab/tools/raytransfer/roughconductor.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/libc/math.pxd.
    Compiling cherab/tools/inversions/sart.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/tools/inversions/voxels.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/tools/plasmas/slab.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/libc/math.pxd.
    Compiling cherab/tools/plasmas/gaussian_volume.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/libc/math.pxd.
    Compiling cherab/tools/primitives/axisymmetric_mesh.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/tools/equilibrium/efit.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/tools/emitters/radiation_function.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/libc/math.pxd.
    Compiling cherab/core/distribution.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/species.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/plasma/material.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/plasma/model.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/plasma/node.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/math/clamp.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/libc/math.pxd.
    Compiling cherab/core/math/samplers.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/math/mappers.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/libc/math.pxd.
    Compiling cherab/core/math/interpolators/utility.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/math/interpolators/interpolators2d.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/math/interpolators/interpolators3d.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/math/interpolators/interpolators1d.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/math/caching/caching3d.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/math/caching/caching2d.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/math/caching/caching1d.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/model/lineshape.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/model/plasma/bremsstrahlung.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/model/plasma/total_radiated_power.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/model/plasma/impact_excitation.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/model/plasma/recombination.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/model/attenuator/singleray.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/model/beam/beam_emission.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/model/beam/charge_exchange.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/beam/material.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/beam/model.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/beam/node.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/utility/constants.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/libc/math.pxd.
    Compiling cherab/openadas/rates/beam.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/openadas/rates/cx.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/openadas/rates/radiated_power.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/openadas/rates/atomic.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/openadas/rates/pec.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/tools/raytransfer/roughconductor.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/libc/math.pxd.
    Compiling cherab/tools/inversions/sart.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/tools/inversions/voxels.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/tools/plasmas/slab.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/libc/math.pxd.
    Compiling cherab/tools/plasmas/gaussian_volume.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/libc/math.pxd.
    Compiling cherab/tools/primitives/axisymmetric_mesh.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/tools/equilibrium/efit.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/tools/emitters/radiation_function.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/libc/math.pxd.
    Compiling cherab/core/distribution.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/species.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/plasma/material.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/plasma/model.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/plasma/node.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/math/clamp.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/libc/math.pxd.
    Compiling cherab/core/math/samplers.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/math/mappers.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/libc/math.pxd.
    Compiling cherab/core/math/interpolators/utility.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/math/interpolators/interpolators2d.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/math/interpolators/interpolators3d.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/math/interpolators/interpolators1d.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/math/caching/caching3d.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/math/caching/caching2d.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/math/caching/caching1d.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/model/lineshape.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/model/plasma/bremsstrahlung.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/model/plasma/total_radiated_power.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/model/plasma/impact_excitation.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/model/plasma/recombination.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/model/attenuator/singleray.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/model/beam/beam_emission.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/model/beam/charge_exchange.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/beam/material.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/beam/model.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/beam/node.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/core/utility/constants.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/libc/math.pxd.
    Compiling cherab/openadas/rates/beam.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/openadas/rates/cx.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/openadas/rates/radiated_power.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/openadas/rates/atomic.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling cherab/openadas/rates/pec.pyx because it depends on /Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Includes/numpy/__init__.pxd.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/drsmith/anaconda3/envs/py38/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
        exitcode = _main(fd, parent_sentinel)
      File "/Users/drsmith/anaconda3/envs/py38/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
        prepare(preparation_data)
      File "/Users/drsmith/anaconda3/envs/py38/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
        _fixup_main_from_path(data['init_main_from_path'])
      File "/Users/drsmith/anaconda3/envs/py38/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
        main_content = runpy.run_path(main_path,
      File "/Users/drsmith/anaconda3/envs/py38/lib/python3.8/runpy.py", line 265, in run_path
        return _run_module_code(code, init_globals, run_name,
      File "/Users/drsmith/anaconda3/envs/py38/lib/python3.8/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/Users/drsmith/anaconda3/envs/py38/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/private/var/folders/d3/rrgnwv_j4xl19brwwb80g4qjmg31yq/T/pip-install-b8zmx0pe/cherab/setup.py", line 65, in <module>
        extensions = cythonize(extensions, nthreads=multiprocessing.cpu_count(), force=force, compiler_directives=cython_directives)
      File "/Users/drsmith/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1078, in cythonize
        pool = multiprocessing.Pool(
      File "/Users/drsmith/anaconda3/envs/py38/lib/python3.8/multiprocessing/context.py", line 119, in Pool
        return Pool(processes, initializer, initargs, maxtasksperchild,
      File "/Users/drsmith/anaconda3/envs/py38/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
        self._repopulate_pool()
      File "/Users/drsmith/anaconda3/envs/py38/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
        return self._repopulate_pool_static(self._ctx, self.Process,
      File "/Users/drsmith/anaconda3/envs/py38/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
        w.start()
      File "/Users/drsmith/anaconda3/envs/py38/lib/python3.8/multiprocessing/process.py", line 121, in start
        self._popen = self._Popen(self)
      File "/Users/drsmith/anaconda3/envs/py38/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
        return Popen(process_obj)
      File "/Users/drsmith/anaconda3/envs/py38/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
        super().__init__(process_obj)
      File "/Users/drsmith/anaconda3/envs/py38/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
        self._launch(process_obj)
      File "/Users/drsmith/anaconda3/envs/py38/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
        prep_data = spawn.get_preparation_data(process_obj._name)
      File "/Users/drsmith/anaconda3/envs/py38/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
        _check_not_importing_main()
      File "/Users/drsmith/anaconda3/envs/py38/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
        raise RuntimeError('''
    RuntimeError:
            An attempt has been made to start a new process before the
            current process has finished its bootstrapping phase.

            This probably means that you are not using fork to start your
            child processes and you have forgotten to use the proper idiom
            in the main module:

                if __name__ == '__main__':
                    freeze_support()
                    ...

            The "freeze_support()" line can be omitted if the program
            is not going to be frozen to produce an executable.
```

The compiling and traceback output repeat many times in the log.

**Comment by drsmith48** [comment]
`python setup.py install` also fails with the same errors for python 3.8.3.

**Comment by jacklovell** [comment]
I suspect this is related to the fact that Python 3.8 on macOS uses the spawn method to start new processes with multiprocessing, whereas Linux (where the code is developed and tested) and Python 3.7 on macOS use the fork method. This is because [fork on macOS is unreliable](https://bugs.python.org/issue33725).

Do note that even if you are able to get cherab to build and install on macOS, performance is likely to be sub-par compared to Linux. This is because the underlying ray tracer, raysect, relies on forking to efficiently run in parallel without the overhead of large memory copies. See https://github.com/raysect/source/issues/269#issuecomment-474157374, as the same issue is present on Windows.

That having been said, you should still be able to install this package and accept the performance hit. You could try removing the `nthreads` argument from this line to get it to build serially: https://github.com/cherab/core/blob/d58c8c26470209be9643a8c23b9dc9385bbe30e9/setup.py#L65

If that works, you may need to do the same thing with raysect (though your pip log doesn't seem to mention attempting to install it: is it already installed?).
