### ISSUE TITLE
configuring atomic data failed

### ISSUE THREAD

**Issue by msubraman** [cherab/core#251]
End up in error while configuring atomic data: 

Python 3.6.9 (default, Oct  8 2020, 12:12:24)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cherab.openadas.repository import populate
>>> populate()
Installing adf11/scd12/scd12_h.dat...
 - downloading ADF file 'adf11/scd12/scd12_h.dat' to '/home/manojsubramani/.cherab/openadas/download_cache/adf11/scd12/scd12_h.dat'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/cherab/openadas/repository/create.py", line 382, in populate
    install_files(rates, download=download, repository_path=repository_path, adas_path=adas_path)
  File "/usr/local/lib/python3.6/dist-packages/cherab/openadas/install.py", line 38, in install_files
    install_adf11scd(*args, download=download, repository_path=repository_path, adas_path=adas_path)
  File "/usr/local/lib/python3.6/dist-packages/cherab/openadas/install.py", line 85, in install_adf11scd
    path = _locate_adas_file(file_path, download, adas_path)
  File "/usr/local/lib/python3.6/dist-packages/cherab/openadas/install.py", line 360, in _locate_adas_file
    urllib.request.urlretrieve(url, target)
AttributeError: module 'urllib' has no attribute 'request'
>>>
--------------------------------------------------------------------------------------

Error appears different way when I run the commands in virtual env.

Python 3.6.9 (default, Oct  8 2020, 12:12:24)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cherab.openadas.repository import populate
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/manojsubramani/core/cherab/openadas/__init__.py", line 19, in <module>
    from .openadas import OpenADAS
  File "/home/manojsubramani/core/cherab/openadas/openadas.py", line 19, in <module>
    from cherab.core import AtomicData
  File "/home/manojsubramani/core/cherab/core/__init__.py", line 21, in <module>
    from .species import *
  File "cherab/core/species.pyx", line 1, in init cherab.core.species
ModuleNotFoundError: No module named 'raysect.core.math.function.function1d'
>>>

**Comment by vsnever** [comment]
It looks like this has already been fixed in the development branch, #186. I think that new release of Cherab is coming soon. For now, @msubraman, can you try calling populate() from ipython instead of plain python? This should work in ipython according to #185.

**Comment by msubraman** [comment]
Thank you @vsnever, that works.
Using ipython, ran without any error.

**Comment by mattngc** [comment]
Appears to be resolved.

**Comment by msubraman** [comment]
yes @mattngc,  resolved. Thank you
