### ISSUE TITLE
Fails to build with up-to-date development branch

### ISSUE THREAD

**Issue by jacklovell** [cherab/core#36]
On up-to-date raysect and cherab core development branches, I can't recompile cherab core (raysect compiles without issue). The problem I'm getting is:
```python
[40/40] Cythonizing demos/gaussian_volume.pyx

Error compiling Cython file:
------------------------------------------------------------
...
# under the Licence.

from libc.math cimport exp
cimport cython

cdef class GaussianVolume(Function3D):
                         ^
------------------------------------------------------------

demos/gaussian_volume.pyx:20:26: First base of 'GaussianVolume' is not an extension type
Traceback (most recent call last):
  File "/home/jlovell/Software/anaconda3/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1164, in cythonize_one_helper
    return cythonize_one(*m)
  File "/home/jlovell/Software/anaconda3/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1146, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: demos/gaussian_volume.pyx
```

This is on my laptop, using Cython 0.28.3.

**Comment by jacklovell** [comment]
Adding the following at the top of [demos/gaussian_volume.pyx]() seems to fix the build issue:
```python
from cherab.core.math.function cimport Function3D
```

But it's strange that this hasn't been needed in the past.

**Comment by jacklovell** [comment]
Building also works fine without the above modification on Cython 0.24, as used on Freia. So it seems to have been caused by a Cython change. Sadly I can't remember what Cython version I used when I last built it, so I'm not sure exactly when this change was introduced.
