### ISSUE TITLE
EFITEquilibrium map_vector3d outside of range?

### ISSUE THREAD

**Issue by Mateasek** [cherab/core#63]
I might have done something wrong, but when I use EFITEquilibrium.map_vector3d to map velocity profiles, I end up with errors:
```
Traceback (most recent call last):
  File "cherab/core/distribution.pyx", line 140, in cherab.core.distribution.Maxwellian.bulk_velocity
  File "cherab/core/math/mappers.pyx", line 212, in cherab.core.math.mappers.VectorAxisymmetricMapper.evaluate
  File "cherab/tools/equilibrium/efit.pyx", line 434, in cherab.tools.equilibrium.efit.FluxCoordToCartesian.evaluate
  File "cherab/tools/equilibrium/efit.pyx", line 342, in cherab.tools.equilibrium.efit.MagneticField.evaluate
  File "cherab/core/math/interpolators/interpolators2d.pyx", line 150, in cherab.core.math.interpolators.interpolators2d._Interpolate2DBase.evaluate
  File "cherab/core/math/interpolators/interpolators2d.pyx", line 223, in cherab.core.math.interpolators.interpolators2d._Interpolate2DBase._dispatch
ValueError: The specified value (x=1.5, y=0.0) is outside the range of the supplied data and/or extrapolation range: x bounds=(0.25, 1.490000000000001), y bounds=(-1.0, 0.9900000000000018)
```

Is it because map_vector3d? I looked into the code and I could not find any line taking care the mapper being asked for value outside of interpolation range  (like for example blending with inside_lcfs).

**Comment by mattngc** [comment]
I think this probably means your input data is out of range.

map_vector3d() just wraps map_vector2d(). In there I can only see Interpolate1DCubic instances. The only thing that would be 2d is the self.psi_normalised function. So this must mean your psi values are going out of range. Have you tried plotting the equilibrium to check its valid? Try evaluating

equilibrium.psi_normalised(1.5, 0.0) and that will probably reveal the problem. Basically, its not in the map_vector3d() machinery, its elsewhere in the equilibrium.

**Comment by CnlPepper** [comment]
Yes, the data point being requested is outside the range of your data:

ValueError: The specified value (x=1.5, y=0.0) is outside the range of the supplied data and/or extrapolation range: x bounds=(0.25, 1.490000000000001), y bounds=(-1.0, 0.9900000000000018)

It appears your equilibrium psi grid only extends to 1.49m, while you are requesting a value at 1.5m.

**Comment by Mateasek** [comment]
Well I knew that it is asking for a value out of the equilibrium. The reason why I put this issue was that scalar interpolation had a built in blending taking care of this issue automatically.  I think this is linked to the newly created issue https://github.com/cherab/core/issues/64#issue-411075102.
